# 应用名称
spring:
  application:
    name: aiot-lab
  #数据源
  datasource:
    url: jdbc:mysql://47.108.94.36:3305/aiot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
#    url: jdbc:mysql://192.168.91.128:3305/aiot?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: nba1234567
#    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: xxx@qq.com
    password: xxxx
    test-connection: false
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: false
        debug: false
        mime:
          splitlongparameters: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.ccww.aiotlab.entity.*
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

token:
  expire: 10000
  secret: F432515A

server:
  port: 80

login:
  md5Num: 10
  salt: qwert

upload:
  imgType: img
  fileType: file
  imgPath: /home/www/upload/img
  filePath: /home/www/upload/file
  pathPatterns: upload

#  imgType: img
#  fileType: file
#  imgPath: F:/upload/img
#  filePath: F:/upload/file
#  pathPatterns: upload




